### ISSUE TITLE
Ausência da dependência SLF4J

### ISSUE THREAD

**Issue by acbarbosa** [acbarbosa/kotlin-javalin-study#2]
Ao inicializar a aplicação (usando `./gradlew run`), temos a seguinte mensagem:

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> -------------------------------------------------------------------
> Missing dependency 'Slf4j simple'. Add the dependency.
> 
> pom.xml:
> <dependency>
>     <groupId>org.slf4j</groupId>
>     <artifactId>slf4j-simple</artifactId>
>     <version>1.7.25</version>
> </dependency>
> 
> build.gradle:
> compile "org.slf4j:slf4j-simple:1.7.25"
> -------------------------------------------------------------------
> Visit https://javalin.io/documentation#logging if you need more help`
> 
> 
> 

Isso indica a ausência da biblioteca de logging requerida. Precisamos adicionar esta dependência

**Comment by marylly** [comment]
Eu já resolvi essa dependência quando estava fazendo funcionar o HELLO WORLD. No commit 49b60d0
